### ISSUE TITLE
Keyboard placement is off when no controllers are active

### ISSUE THREAD

**Issue by atonalfreerider** [Logitech/logi_bridge_sdk#10]
If the Vive tracker is the only active tracked object in SteamVR, the keyboard gets placed at the center of the room.

**Comment by mmeisser** [comment]
That should not be the case: in our setup we often have only one Vive tracker active (and on) and the keyboard model should be placed there. Please check it again with the latest release 1.2 (build 24) and make sure to shake a bit the tracker to make sure it is well tracked by the system,
