### ISSUE TITLE
virtual keyboard appears too close

### ISSUE THREAD

**Issue by TaylorR137** [Logitech/logi_bridge_sdk#5]
The virtual keyboard appears to close to my head when I move away from the desk. When I go through setup at a comfortable typing positon it looks pretty good. Its not rock solid like every other tracked object I've used though. When I am ~8 feet away the keyboard appears floating at about arms length.

**Comment by trouvinez** [comment]
Thank you for taking the time to test Bridge and reporting this issue.

It seems to be a byproduct of the re-projection we do to render the overlay. As it is not perfect, the keyboard might sometimes seem a bit "off" in terms of pose and size.

We are working on improving this. Would it help if we were to hide the keyboard if you are standing far from it ?

**Comment by TaylorR137** [comment]
Its certainly possible to get the composited image reprojected right.  OVRDrop on Steam, formerly https://github.com/Hotrian/OpenVRDesktopDisplayPortal  . does it really well with your desktop or a window attached to a controller. 

It would help if it faded away or became a small icon, but It its very important to get the tracking right and render the keyboard for both eyes.

**Comment by Gabriele333** [comment]
the tracker on the side is perfectly tracked in VE. possibly because OpenVR handles it. Couldn't you deploy the keyboard render to OpenVR?

**Comment by mmeisser** [comment]
Hello Gabriele, thanks for your comment. Indeed if we were to directly offer the 3d model to the app, then openVR would be able to render it accordingly, as it does with the controllers (the app can override the 3d model of the controller). Since we use the SteamVR overlay technique, in order to allow any app to work with our keyboard off-the-shelf (no code change required), such option is not available unfortunately. That said we are working on improving the re-projection method we use, so it might come out in one updated release. we'll keep you posted and update this issue when this happens.

**Comment by Gabriele333** [comment]
Hi mmeisser, I suspected that, however by doing so the risk is that you screw up the whole experience and make the whole SDK not usable. I'd rather focus folks who can code first, once you get a set of great case studies then you'd work on a more generic/compatible solution IMHO. Also, you could easily do both :) Amyway, thank you for your support, this project is amazing!

**Comment by mmeisser** [comment]
Gabriele, I agree with you: In fact others have been asking about a more integrated (ie Unity/Unreal plugin) solution. We are working on making that available, so stay tuned !

**Comment by mmeisser** [comment]
@Gabriele333 : no Integrated plugin (yet), but we have just released version 2.0 that is doing a much better job for the reprojection of the keyboard. It is not perfect, but the spatial rendering of the keyboard should be better now. Also we added support for stereo rendering, so it should be easier to "judge" the size and distance of the rendered object (keyboard) now.
