### ISSUE TITLE
Camera error message above keyboard even with camera off

### ISSUE THREAD

**Issue by TaylorR137** [Logitech/logi_bridge_sdk#6]
I'm presently using the TPCast wireless module with my vive which means the camera is not available. I'd like to use the logitech bridge overlay anyway, but the error message that appears in blue above the keyboard is rather annoying. I have the hand overlay disabled in the logitech bridge software.

**Comment by mmeisser** [comment]
Hey Taylor. We indeed thought about the issue, and indeed, if the camera is not available (as in the TPCast solution) the hands layer must be then disabled (you can use the toggle in the Desktop UI). By the way those settings are stored, so you would need to change that only once.

**Comment by mmeisser** [comment]
No automatic detection is implemented when no camera is available, but the UI allows to toggle hands layer visibility to avoid the issue.
