### ISSUE TITLE
Vive Pro Support

### ISSUE THREAD

**Issue by atonalfreerider** [Logitech/logi_bridge_sdk#9]
Is there going to be support for the Vive Pro in an upcoming release? It appears that the dual cameras are causing issues tracking hands currently.

**Comment by mmeisser** [comment]
Hello John, 
We already are testing it on our side, but there is no precise release date for that. please stay tuned! By the way we plan on releasing an updated version in a few weeks with much better visual rendering !

**Comment by ciaran-worcester** [comment]
Has any progress been made on this?
Do you have a rough idea when it will be updated to include pro support?

**Comment by mmeisser** [comment]
Ciaran, apologies for making promises that we could not keep:  We actually have a working demo, and we should release it in order to get some feedback. check back in august for that.

**Comment by mmeisser** [comment]
@ciaran-worcester : we're finally there: release 2.0 is now adding support for vivePro and a new reprojection algorithm. Give it a try !

**Comment by ciaran-worcester** [comment]
Brilliant, thank you 
Will give it a test today
